<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>true</IsPackable>
  <PackageId>FlowORM.Net.SqlServer</PackageId>
  <Description>SQL Server provider for FlowORM.Net.</Description>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../FlowORM.Net/FlowORM.Net.csproj"/><PackageReference Include="Microsoft.Data.SqlClient"/></ItemGroup>
</Project>
